const items = [
  {
    itemImage: 'https://www.patagonia.com/dw/image/v2/BDJB_PRD/on/demandware.static/-/Sites-patagonia-master/default/dw3d461566/images/hi-res/25528_PGBE.jpg?sw=1920&sh=1920&sfrm=png&q=90&bgcolor=ffffff',
    itemName: 'Unisex Jacket',
    itemPrice: 60,
    itemDetails: 'This warm, 100% recycled polyester full-zip jacket combines a sweater-knit aesthetic with the easy care of Better Sweater fleece. It’s dyed with a low-impact process that significantly reduces the use of dyestuffs, energy and water compared to conventional dyeing methods.',
  },
  {
    itemImage: 'https://www.patagonia.com/dw/image/v2/BDJB_PRD/on/demandware.static/-/Sites-patagonia-master/default/dw5b1eb15a/images/hi-res/84212_LMBE.jpg?sw=512&sh=512&sfrm=png&q=95&bgcolor=ffffff',
    itemName: 'Unisex Puff Jacket',
    itemPrice: 80,
    itemDetails: 'Warm, windproof, water-resistant—the Better Sweater Puff Jacket uses incredibly lightweight and highly compressible 60-g PrimaLoft® Gold Insulation Eco 100% postconsumer recycled polyester with P.U.R.E.™ (Produced Using Reduced Emissions) technology, wrapped in a 100% recycled polyester shell and lining.',
  },
  {
    itemImage: 'https://www.patagonia.com/dw/image/v2/BDJB_PRD/on/demandware.static/-/Sites-patagonia-master/default/dw431040e4/images/hi-res/27920_BLK.jpg?sw=512&sh=512&sfrm=png&q=95&bgcolor=ffffff',
    itemName: 'Unisex Glacier Jacket',
    itemPrice: 110,
    itemDetails: 'A sophisticated wind- and weatherproof jacket insulated with warm 700-fill-power 100% Recycled Down (duck and goose down reclaimed from down products).',
  },
  {
    itemImage: 'https://www.patagonia.com/dw/image/v2/BDJB_PRD/on/demandware.static/-/Sites-patagonia-master/default/dwa60613e5/images/hi-res/47913_BLYB.jpg?sw=512&sh=512&sfrm=png&q=95&bgcolor=ffffff',
    itemName: 'Refugio Daypack',
    itemPrice: 65,
    itemDetails: 'The Refugio Daypack has the go-to volume and fit built for efficient working on the go and capable gear carrying on the trail, with the ability to tackle any pursuit in between. Made with 100% recycled body fabric, lining and webbing.',
  },
  {
    itemImage: 'https://www.patagonia.com/dw/image/v2/BDJB_PRD/on/demandware.static/-/Sites-patagonia-master/default/dw945249ed/images/hi-res/49342_BLYB.jpg?sw=512&sh=512&sfrm=png&q=95&bgcolor=ffffff',
    itemName: 'Black Hole Duffel Bag',
    itemPrice: 110,
    itemDetails: 'Our go-to Duffel for the adventures. This 55-liter workhorse organizes your gear and has enough space for a fun-hog weekend or a well-organized extended trip. Made with 100% recycled body fabric, lining and webbing.',
  },
  {
    itemImage: 'https://www.patagonia.com/dw/image/v2/BDJB_PRD/on/demandware.static/-/Sites-patagonia-master/default/dwdde21bd3/images/hi-res/29105_NUVG.jpg?sw=512&sh=512&sfrm=png&q=95&bgcolor=ffffff',
    itemName: 'Rolled Beanie',
    itemPrice: 20,
    itemDetails: 'A soft, skin-friendly, everyday beanie made with an itch-free 100% recycled polyester yarn.',
    margin: true,
  },
  {
    itemImage: 'https://contents.mediadecathlon.com/p192895/4f35515e457ceabdbc652deeb023ebc357f26bbb9b140289685e8960c3777a27/3-person-camping-tent-2-seconds-fresh-black-white.jpg?f=576x0&format=auto',
    itemName: 'Quechua Camping Tent',
    itemPrice: 100,
    itemDetails: 'Treat yourself to comfort: spacious bedroom, good height under the roof, and the Fresh & Black technology that offers coolness and darkness for a good sleep. No more frustration when heading off with our Easy folding. Made from 100% recycled materials',
    margin: true,
  },
  {
    itemImage: 'https://contents.mediadecathlon.com/p2315792/6b667bf5a927c5ba8ff011afa91416a1bc20b5e50062dd77718b77f6b168c3a8/mens-hiking-mid-shoes-mh-500-brown.jpg?f=576x0&format=auto',
    itemName: 'Quechua Hiking Boots',
    itemPrice: 80,
    itemDetails: 'Light, comfortable, and waterproof. The mid-height upper will give you greater protection as well as comfort on trails. The sole has our Outdoor Contact technology to provide really good grip. A rubber toe bumper also gives you extra protection. Made from natural fibres and recycled materials.',
    margin: true,
  },
  {
    itemImage: 'https://contents.mediadecathlon.com/p1064413/6073c1dc3d4a958f42ba5a6a107d0a5fe5597603705ee52d8f18d555c210f7bd/2-seat-inflatable-kayak-kti-100-green.jpg?f=576x0&format=auto',
    itemName: '2-Seat Inflatable Kayak',
    itemPrice: 250,
    itemDetails: 'A beginners’ touring kayak for solo or tandem half-day trips. It also fits in the trunk of your car. The pump and the paddle are also included. This inflatable kayak has 2 raised seats and a comfortable, stable design. Made with 100% recycled polyester.',
    margin: true,
  },
  {
    itemImage: 'https://contents.mediadecathlon.com/p2332576/a13e37e2ac151aa082cb60a6cb0101b00a9fe2e336025ee7afd872a63ee556bb/kids-downhill-skis-with-bindings-boost-500-white-yellow.jpg?f=576x0&format=auto',
    itemName: 'Downhill Skis',
    itemPrice: 95,
    itemDetails: 'Perfect for all kinds of ski runs! These skis are great for learning. The sidecut and flex of these skis make them perfect for helping young skiers progress quickly.',
  },
  {
    itemImage: 'https://contents.mediadecathlon.com/p1626014/6a1aa13100e0cb1f2fbd8abe4c885e05ef160e756878f6924236c53caea5594e/adjustable-mountain-bike-helmet-500kids.jpg?f=576x0&format=auto',
    itemName: 'Rockrider Bike Helmet',
    itemPrice: 30,
    itemDetails: 'Ride safely! This helmet is designed to protect your head during bike rides. Light and comfortable: perfect for biking. Good ventilation thanks to the vents. The pre-set straps make it easy to adjust. Made from tough and recycled Polycarbonates.',
    margin: true,
  },
  {
    itemImage: 'https://contents.mediadecathlon.com/p2373123/d291c3ebf09d35b0b484f5e3ec3cfac937187e264075358da3994858f7a0af7a/29-eagle-mountain-bike-race-100-s-eagle-blue.jpg?f=576x0&format=auto',
    itemName: 'Rockrider XC-100 MTB',
    itemPrice: 900,
    itemDetails: 'This full suspension frame with 120mm travel provides control on rough terrain. Our go-to bike for exploring and mountain biking, perfect for adventure seekers. Made with tough aluminum and carbon while keeping in mind aerodynamics. Bikes are a sustainable mode of transport!',
    margin: true,
  },
];